# Generated by Django 4.1 on 2024-02-24 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("date_naissance", models.DateField()),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1
                    ),
                ),
                ("adresse", models.TextField()),
                ("wilaya", models.CharField(max_length=255)),
                ("telephone", models.CharField(max_length=15)),
                ("personne_a_contacter", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("numero_secu_sociale", models.CharField(max_length=20)),
                (
                    "affiliation",
                    models.CharField(
                        choices=[
                            ("Assuré", "CNAS"),
                            ("Ayant droit", "CASNOS"),
                            ("Démuni", "Démuni"),
                            ("Non assuré", "Non assuré"),
                        ],
                        default="Assuré",
                        max_length=11,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TraitementMedical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("traitement_en_cours", models.TextField()),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TraitementEndovasculaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coiling", models.CharField(max_length=255)),
                ("coiling_assiste_balonnet", models.CharField(max_length=255)),
                ("coiling_assiste_stent", models.CharField(max_length=255)),
                ("flow_diverter", models.CharField(max_length=255)),
                ("autres", models.TextField()),
                ("reconstruction", models.TextField()),
                ("quantification_unites", models.IntegerField()),
                ("codification_acte", models.CharField(max_length=255)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Traitement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("traitement_antiepileptique", models.TextField()),
                ("therapie_triple_h", models.TextField()),
                ("drogues_vasoactives", models.TextField()),
                ("vasodilatateurs", models.TextField()),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SuiviMedical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequence_consultations_3mois", models.BooleanField()),
                ("frequence_consultations_12mois", models.BooleanField()),
                ("consultation_post_op_demande", models.BooleanField()),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Radiochirurgie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnostic", models.TextField()),
                ("code_cim", models.CharField(max_length=255)),
                ("embolisation_prealable", models.BooleanField()),
                ("nb_seances_embolisation", models.IntegerField()),
                ("microchirurgie_prealable", models.BooleanField()),
                ("nb_operations_microchirurgie", models.IntegerField()),
                ("codification_acte", models.CharField(max_length=255)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriseEnCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("traitement_medical", models.TextField()),
                ("reeducation_fonctionnelle", models.TextField()),
                ("traitement_suivi_comorbidites", models.TextField()),
                ("prise_en_charge_psychologique", models.TextField()),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Microchirurgie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_traitement", models.TextField()),
                ("operation_1", models.TextField()),
                ("operation_2", models.TextField()),
                ("operation_3", models.TextField()),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoireMaladie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptomes_revelateurs", models.TextField()),
                ("date_debut", models.DateField()),
                ("duree", models.TextField()),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exploration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tdm_cerebrale", models.TextField()),
                ("score_fisher", models.FloatField()),
                ("angio_scanner_cerebral", models.TextField()),
                ("irm_cerebrale", models.TextField()),
                ("angiographie_cerebrale", models.TextField()),
                ("doppler_transcranien", models.TextField()),
                ("autres_explorations", models.TextField()),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamensImagerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("angiographie_controle_3_6mois", models.BooleanField()),
                ("angiographie_controle_12mois", models.BooleanField()),
                ("angiographie_controle_24mois", models.BooleanField()),
                ("angio_irm_angioscanner_suivi_tardif", models.BooleanField()),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvolutionSymptomes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nouveaux_symptomes", models.TextField()),
                ("amelioration_symptomes", models.TextField()),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationPostOp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evaluation", models.TextField()),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EtatNeurologique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("score_wfns", models.FloatField()),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EtatClinique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("groupe_sanguin", models.CharField(max_length=10)),
                ("taille", models.FloatField()),
                ("poids", models.FloatField()),
                ("imc", models.FloatField()),
                ("ta", models.CharField(max_length=15)),
                ("temperature", models.FloatField()),
                ("respiration", models.CharField(max_length=15)),
                ("fr", models.FloatField()),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diagnostic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maladie", models.TextField()),
                ("code_cim", models.CharField(max_length=10)),
                ("lesion_unique_rompue", models.BooleanField()),
                ("lesion_multiple_non_rompue", models.BooleanField()),
                ("pathologie_associee", models.TextField()),
                ("code_cim_pathologie_associee", models.CharField(max_length=10)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Complications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saignement_siege", models.TextField()),
                ("delais_saignement", models.FloatField()),
                ("decision_thérapeutique_saignement", models.TextField()),
                ("acte_medicochirurgical_saignement", models.CharField(max_length=255)),
                ("resultats_saignement", models.TextField()),
                ("hydrocephalie", models.TextField()),
                ("decision_thérapeutique_hydrocephalie", models.TextField()),
                ("delais_apparition_hydrocephalie", models.FloatField()),
                (
                    "acte_medicochirurgical_hydrocephalie",
                    models.CharField(max_length=255),
                ),
                ("resultats_hydrocephalie", models.TextField()),
                ("vasospasme_localisation", models.TextField()),
                ("deficit_neurologique_vasospasme", models.TextField()),
                (
                    "acte_medical_interventionnel_vasospasme",
                    models.CharField(max_length=255),
                ),
                ("resultats_vasospasme", models.TextField()),
                ("epilepsie_traitement_medical", models.TextField()),
                ("resultats_epilepsie", models.TextField()),
                ("complications_liees_acte", models.TextField()),
                ("acte_medicochirurgical_autres", models.CharField(max_length=255)),
                ("resultats_autres", models.TextField()),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chirurgie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_chirurgie", models.TextField()),
                ("resultats_complications", models.TextField()),
                ("dates_details_interventions", models.TextField()),
                ("commentaires", models.TextField()),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AutresSignesCliniques",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Antecedent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maladies_chroniques", models.TextField()),
                ("allergies_medicamenteuses", models.TextField()),
                ("medicaments_en_cours", models.TextField()),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnomalieGenetique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anomalie_connue", models.TextField()),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurorad_core.patient",
                    ),
                ),
            ],
        ),
    ]
